- cc-mage/custom/drop_city_transport_staging.sql
- cc-mage/data_exporters/export_google_curb.py
- cc-mage/data_exporters/export_google_ipcc_ef_staging.py
- cc-mage/data_loaders/load_curb_transport.py
- cc-mage/data_loaders/load_google_ipcc_ef.py
- cc-mage/data_loaders/update_city_transport_activity.sql
- cc-mage/data_loaders/update_city_transport_ef.sql
- cc-mage/data_loaders/update_city_transport_emissions.sql
- cc-mage/data_loaders/update_city_transport_gpcmethod.sql
- cc-mage/pipelines/google_eie_file/metadata.yaml
- cc-mage/transformers/raw_data_google_emissions.sql
- cc-mage/transformers/transform_city_residential.sql
- cc-mage/transformers/transform_city_transport.sql
- cc-mage/transformers/transform_google_ef.sql
- Added emissions factor for activity data in google eie
- Replaced the total co2eq estimations with emissions disaggregated by gas
> feat: added activity data for google eie and gas emissions

- cc-mage/data_exporters/update_seeg_sector_staging.py
- cc-mage/data_loaders/load_ipcc_to_gpc.py
- cc-mage/data_loaders/load_seeg_to_ipcc.py
- cc-mage/data_loaders/update_see_sector_activity.sql
- cc-mage/data_loaders/update_seeg_sector_emissions.sql
- cc-mage/local_scripts/seeg_file_to_rawdata.sql
- cc-mage/markdowns/seeg_data_pipeline.md
- cc-mage/pipelines/seeg_br_file/metadata.yaml
- cc-mage/transformers/transform_seeg_to_gpc.sql
- added pipeline to model seeg emissions to gpc based on a mapping template
- this does not cover waste and most of energy scope 2 emissions
- seeg only has emissions data there is no activity data or emission factors.
> feat added seeg pipeline for modelled emissions

- cc-mage/data_exporters/import_bechmark_data.py
- cc-mage/data_loaders/benchmark_file_read_s3.py
- cc-mage/data_loaders/loading_emissions_data.py
- cc-mage/data_loaders/loading_gwp.py
- cc-mage/pipelines/metadata.yaml
- cc-mage/transformers/applying_benchmark.py
- cc-mage/transformers/applying_gwp.py
This PR contains the pipeline to verify the emissions values ​​against the C40 reference bounds; the sequence was applied to the "emissions" table for city level emissions.
> feat:pipeline for benchmark

- cc-mage/data_loaders/load_brazil_cities.py
- cc-mage/data_loaders/load_brazil_unlocodes.py
- cc-mage/data_loaders/upsert_brazil_cities.sql
- cc-mage/pipelines/overturemaps_city_boundary/metadata.yaml
- cc-mage/transformers/transform_brazil_cities.sql
Refactor the data loading and transformation process for Brazilian city boundary data to utilize the recommended city polygons and update configuration, SQL transformations, and metadata accordingly.
These changes are made to improve data accuracy and reliability by using standardized city polygons, which are sourced from a newly specified S3 bucket location using configuration settings from 'io_config.yaml'. This approach consolidates how data is fetched and handled, thus eliminating the need for manual AWS credential handling and reducing the likelihood of inconsistencies in city data transformations. Additionally, unnecessary code for credentials has been commented out, and region handling in transformations has been streamlined through the introduction of a new `region_mapping` and …
> updated pipeline with recommended city polygons

- .github/workflows/mage-ai-develop.yml
Update the GitHub Actions workflow to modify the paths triggering the workflow, adjust job definitions, and refine steps to push the mageai image to GHCR under a new directory structure.
These changes align the workflow with the updated directory structure and ensure that pipeline triggers reflect the correct scope of files. This update simplifies the workflow and maintains continuous deployment practices by pushing the latest image whenever relevant code changes are committed.
> update actions to update image

- cc-mage/data_exporters/load_icare_city_locode_db.py
- cc-mage/data_exporters/load_icare_city_topology_db.py
- cc-mage/data_exporters/load_icare_emission_forecast_rate_db.py
- cc-mage/data_loaders/load_icare_city_locode.py
- cc-mage/data_loaders/load_icare_city_topology.py
- cc-mage/data_loaders/load_icare_emission_forecast_rate.py
- cc-mage/pipelines/ghgi_icare_emission_forecast/metadata.yaml
- cc-mage/transformers/update_forecast_emission_icare.sql
Add a data pipeline to forecast emissions by loading data from S3, exporting it to a PostgreSQL database, and updating the forecast in the target database, including the creation of metadata for the pipeline and a SQL transformer.
These changes enhance the system by automating emissions forecast data processing, leveraging new data sources to support strategic decision-making. The inclusion of both data loaders and exporters ensures smooth data transition from raw inputs to actionable reports while maintaining data integrity and efficiency through consistent processes.
> added pipeline for emissions forecast

- cc-mage/datasets/datasource_seeder.yaml
Add Portuguese translations to the `datasource_seeder.yaml` file for dataset names, descriptions, methodology descriptions, and transformation descriptions.
To enhance the system's accessibility and usability for Portuguese-speaking users by providing localized content, which is important for engagement and comprehension in regions where Portuguese is the primary language, such as Brazil. This change also aligns with the platform’s goal to offer multi-language support for its datasets.
> feat: Adding Portuguese translations

- cc-mage/data_exporters/ippu_ct_staging.py
- cc-mage/data_exporters/update_ippu_ct_emission_factor.sql
- cc-mage/data_exporters/update_ippu_ct_emissions.sql
- cc-mage/data_exporters/update_ippu_ct_sector_activity.sql
- cc-mage/data_loaders/load_raw_ippu_ct.py
- cc-mage/pipelines/ghgi_ippu_climatetrace/metadata.yaml
- cc-mage/transformers/cleaning_ippu_ct.py
- cc-mage/transformers/ct_country_code_lookup.sql
- cc-mage/transformers/locode_transformation.sql
- cc-mage/transformers/transformation_ippu_ct.py
Implement a new data processing pipeline for the `ippu_ct` module, involving loading and transforming industry emissions data, exporting it to a PostgreSQL database, and updating emissions-related tables.
The changes provide a comprehensive process for handling industrial emissions data by reading it from multiple CSV files stored in an S3 bucket, transforming it to align with industry subcategories, calculating emissions, and exporting structured data to PostgreSQL. This approach improves data management, ensures consistency, and enhances downstream data analysis capabilities.
> On 1011 ippu ct

- cc-mage/data_exporters/load_icare_forecast_historical_db.py
- cc-mage/data_loaders/load_icare_forecast_historical_rate.py
- cc-mage/pipelines/ghgi_icare_emission_forecast/metadata.yaml
- cc-mage/transformers/update_forecast_emission_icare.sql
- cc-mage/transformers/update_forecast_historical.sql
Add functionality to load and export historical growth rates data to the PostgreSQL database and update the ICare forecast pipeline to include processing of historical growth rates data.
The updates enable historical growth rates data to be imported from an S3 bucket, processed and exported to a PostgreSQL database, and integrated into the emissions forecast model, facilitating enhanced predictive analysis and better decision-making based on historical data trends. This allows the ICare forecast pipeline to provide a more comprehensive analysis by considering past emissions growth rates.
> feat added historical growth rates

- cc-mage/datasets/datasource_seeder.yaml
Modify the `geographical_location` from "Brasil" to "BR" and update `api_endpoint` paths in the `datasource_seeder.yaml` file for multiple datasets.
These changes ensure consistency and adherence to standard formats by using the ISO 3166-1 alpha-2 country code ("BR") instead of the full country name ("Brasil"), and by updating endpoint paths to use a standardized format, improving API integration and data retrieval processes.
> fix: names changed

- cc-mage/data_loaders/load_dataseeder_github.py
- cc-mage/datasets/datasource_seeder.yaml
- cc-mage/pipelines/dataseeder_fileload/metadata.yaml
Add testing for dataseeder file with assertions to verify valid API endpoint patterns and update datasource seeder and metadata configurations.
To ensure the API endpoints in the dataseeder file conform to expected patterns, enhancing data integrity and consistency. The updates to the datasource configuration reflect the current year, and the metadata changes address the pipeline execution status, aligning it with the new testing logic.
> added testing for dataseeder file

- cc-mage/data_exporters/update_seeg_sector_staging.py
- cc-mage/data_loaders/update_see_sector_activity.sql
- cc-mage/data_loaders/update_seeg_sector_emissions.sql
- cc-mage/datasets/datasource_seeder.yaml
- cc-mage/pipelines/ghgi_seeg_br/metadata.yaml
- cc-mage/transformers/transform_seeg_to_gpc.sql
Enhance the SEEG data import and transformation processes by including more granular activity subcategories, updating API endpoints, and amending data staging configurations.
These changes improve the precision of emissions data classification by incorporating subcategory differentiation, align the system with updated data source endpoints (from `v0` to `v1`), and optimize data handling by transitioning to the 'raw_data' schema for initial staging, thus facilitating better data management and reporting accuracy.
> feat-addded-activity-names-seeg

- cc-mage/data_exporters/ippu_ct_staging.py
- cc-mage/data_exporters/update_ippu_ct_emission_factor.sql
- cc-mage/data_exporters/update_ippu_ct_emissions.sql
- cc-mage/data_exporters/update_ippu_ct_sector_activity.sql
- cc-mage/data_loaders/load_raw_ippu_ct.py
- cc-mage/data_loaders/update_ct_oil_activity_subcategory.sql
- cc-mage/datasets/datasource_seeder.yaml
- cc-mage/pipelines/ghgi_climate_trace_oil_and_gas_refining/metadata.yaml
- cc-mage/pipelines/ghgi_ippu_climatetrace/metadata.yaml
- cc-mage/transformers/ct_country_code_lookup.sql
- cc-mage/transformers/locode_transformation.sql
- cc-mage/transformers/transformation_ippu_ct.py
Update activity and data source names across multiple SQL and Python scripts to align with the seeder schema changes while also modifying metadata configurations to reflect execution status adjustments.
The updates are necessary to maintain consistency with recent changes in data seeder conventions, specifically the standard naming format for datasources as 'ClimateTRACEv2024.' Additionally, metadata execution status changes align with the current pipeline status and address enhancements for performance improvements.
> feat updated activity names and datasources to align with seeder

- cc-mage/pipelines/ghgi_ippu_climatetrace/metadata.yaml
- cc-mage/transformers/ct_country_code_lookup.sql
- cc-mage/transformers/locode_transformation.sql
Update SQL scripts to enhance the climate trace IPPU data processing including schema changes, data aggregation, and table restructuring.
The changes improve data processing by ensuring existing tables are dropped before new data is inserted to prevent duplicates, and by aggregating emissions data for better organization and querying. This approach also updates data versioning and modifies the database schema to fit the updated data structure.
> feat adding details for climate trace ippu

- cc-mage/data_loaders/import_raw_snis_from_s3.py
- cc-mage/data_loaders/update_snis_emission_factor.sql
- cc-mage/data_loaders/update_snis_emissions.sql
- cc-mage/data_loaders/update_snis_sector_activity.sql
- cc-mage/pipelines/ghgi_snis_waste_water_brazil/metadata.yaml
- cc-mage/pipelines/overturemaps_city_boundary/metadata.yaml
- cc-mage/transformers/ch4_calculation_snis.py
- cc-mage/transformers/cleaning_snis.py
- cc-mage/transformers/n2o_calculation_snis.py
- cc-mage/transformers/scope_assignation_snis.py
- importer/SNIS-brasil/raw_data_snis.csv
- importer/SNIS-brasil/transformation_snis.ipynb
Refactor the import script to allow dynamic S3 bucket selection, introduce subcategories in SNIS data processing, enhance SQL with conflict handling for emissions, and revise transformations to incorporate treatment subcategory details and region codes.
These changes improve flexibility and accuracy in data processing and emission calculations for the SNIS project by allowing for region-specific data handling and providing more detailed classifications in activity data. Dynamic bucket selection improves adaptability to different environments or datasets, while conflict handling in SQL ensures data consistency.
> feat added subcategories and updated for region codes

- cc-mage/custom/cleaning_oil_gas_refining_ct.py
- cc-mage/custom/gpc_methodology_info.py
- cc-mage/data_exporters/fugitive_ct_staging.py
- cc-mage/data_exporters/ingest_raw_oil_gas_refining_ct.py
- cc-mage/data_exporters/update_fugitive_ct_ef.sql
- cc-mage/data_exporters/update_fugitive_ct_emissions.sql
- cc-mage/data_exporters/update_fugitive_ct_sector_activity.sql
- cc-mage/data_loaders/oil_gas_refining_read_s3.py
- cc-mage/markdowns/overview.md
- cc-mage/pipelines/ghgi_climate_trace_oil_and_gas_refining/metadata.yaml
- cc-mage/pipelines/gpc_methodology/metadata.yaml
- cc-mage/transformers/cleaning_fugitive_oil_ct.py
- cc-mage/transformers/locode_transformation.sql
Refactor the climate trace emissions pipeline for oil and gas refining to enhance data processing, consolidate data handling, and update database interactions, including the introduction of new SQL scripts for emissions factor and sector activity updates, and a new transformer for cleaning fugitive oil data.
These changes aim to streamline the data processing pipeline for handling oil and gas fugitive emissions, improving data accuracy and processing efficiency by ensuring consistent data types, consolidating inputs from multiple CSV sources, and refactoring the naming and storage structure for better alignment with Climate TRACE requirements. The updates reflect a transition towards more efficient data management and relevantly address stakeholder requirements for fossil fuel emission …
> feat: fugitive emissions oil and gas pipeline

- cc-mage/custom/fugitive_emissions_custom.py
- cc-mage/data_exporters/coal_ct_staging.py
- cc-mage/data_exporters/coal_mining_staging.sql
- cc-mage/data_exporters/update_coal_ct_activity_subcategory.sql
- cc-mage/data_exporters/update_coal_ct_emissionfactor.sql
- cc-mage/data_exporters/update_coal_ct_emissions.sql
- cc-mage/data_loaders/coal_minig_ct_read_s3.py
- cc-mage/pipelines/ghgi_climate_trace_coal/metadata.yaml
- cc-mage/pipelines/gpc_methodology/metadata.yaml
- cc-mage/transformers/cleaning_coal_mining_ct.py
- cc-mage/transformers/locode_transformation_coal_ct.sql
Implement the "ghgi_climate_trace_coal" pipeline by adding data loading, transformation, and exporting functionalities, along with SQL scripts for updating activity subcategories, emission factors, and emissions within the database.
These changes enable the integration and processing of coal mining emissions data from S3 storage into a structured PostgreSQL database schema, enhancing data accessibility for subsequent analysis and reporting as part of the Climate TRACE initiative. This approach standardizes the processing with custom methodologies and aligns the emissions data with existing data models, although the complexity and dependencies mean database migration and configuration management should be thoroughly tested in the target environment.
> Is this description stale? Ask me to …
> feat: coal pipeline

- cc-mage/datasets/datasource_seeder.yaml
Add fugitive emissions data from ClimateTRACEv2024 for coal mining and oil & gas production, integrating new datasets into `datasource_seeder.yaml` with relevant metadata and methodologies.
This enhancement supports more comprehensive accounting of greenhouse gas (GHG) emissions by leveraging extensive third-party data sources, which cover diverse emission sources and apply sophisticated methodologies for estimation. It enhances the dataset's granularity and overall data coverage, critical for tracking and managing emissions effectively.
> feat: adding fugitive emissions from ClimateTRACEv2024

- cc-mage/data_exporters/sinir_staging.py
- cc-mage/data_loaders/update_sinir_emission_factors.sql
- cc-mage/data_loaders/update_sinir_emissions.sql
- cc-mage/data_loaders/update_sinir_sector_activity.sql
- cc-mage/pipelines/ghgi_sinir_solidwaste_brasil/metadata.yaml
- cc-mage/transformers/biological_calculation_sinir.py
- cc-mage/transformers/cleaning_sinir.py
- cc-mage/transformers/clinical_waste_calculation_sinir.py
- cc-mage/transformers/incineration_calculation_sinir.py
- cc-mage/transformers/solid_waste_calculation_sinir.py
Incorporate subcategories and region into SQL join conditions across multiple data loaders and transformers and update schema references from 'modelled' to 'raw_data'.
The changes aim to enhance data accuracy and integrity by including subcategory details and region codes in joins and identifier constructions, reflecting a more precise representation of the data. Transitioning to the 'raw_data' schema supports a uniform schema application, while involving DuckDB for handling JSON metadata improves processing efficiency in the codebase.
> feat added subcategories and region to join condition

- cc-mage/data_exporters/load_br_national_inventory_db.py
- cc-mage/data_exporters/load_c40_inventories_db.py
- cc-mage/data_exporters/load_cc_manual_input_json_db.py
- cc-mage/data_exporters/load_cc_translation_string_db.py
- cc-mage/data_loaders/country_name_lookup.sql
- cc-mage/data_loaders/load_br_national_inventory.py
- cc-mage/data_loaders/load_c40_inventories.py
- cc-mage/data_loaders/load_cc_manual_input_json.py
- cc-mage/data_loaders/load_cc_translation_string.py
- cc-mage/data_loaders/raw_data_globalapi_emissions.sql
- cc-mage/pipelines/dq_alignment_globalapi_and_cc/metadata.yaml
- cc-mage/pipelines/dq_ghgi_datavalidation/metadata.yaml
- cc-mage/transformers/missing_translation_strings_cc.sql
- cc-mage/transformers/raw_data_c40_locode_inventories.sql
- cc-mage/transformers/transform_c40_database.sql
- cc-mage/transformers/transformation_cc_manual_input.sql
Add new data loader and exporter scripts to handle data ingestion from S3, API, and local files into a PostgreSQL database, alongside SQL scripts to create and transform relevant data tables for data quality validation in the City Catalyst data pipelines.
This change is being made to enhance data integration and facilitate the management of emissions data by automating the ingestion process into the database, followed by structured data alignment through SQL transformations. The approach uses standardized methods for loading configurations, ensuring consistent and reliable data handling while leveraging existing operational setups for ease of integration.
> fix updating data quailty pipeline

- cc-mage/data_loaders/update_dataseeder.sql
- cc-mage/datasets/datasource_seeder.yaml
- cc-mage/pipelines/dataseeder_fileload/metadata.yaml
Add a "priority" field to each datasource entry in the `datasource_seeder.yaml` file.
These changes are being made to enhance the datasource configuration by introducing a priority setting, allowing for more nuanced management of these resources. The addition supports better task scheduling or allocation based on the urgency or importance of different datasources within the system, ensuring that the system can be optimized according to business needs and priorities.
> feat: adding priority field

- cc-mage/datasets/climate_actions/climate_actions_en.json
- cc-mage/datasets/climate_actions/climate_actions_es.json
- cc-mage/datasets/climate_actions/climate_actions_pt.json
Added climate action data
Upload JSON data files for climate actions in English, Spanish, and Portuguese.
These changes are made to provide localized datasets of climate actions for better accessibility and usability in multiple languages. This upload supports the platform's goal to offer comprehensive resources across different regions and linguistic groups.
> chore: uploaded data for climate actions

- cc-mage/data_loaders/update_dataseeder.sql
- cc-mage/datasets/datasource_seeder.yaml
- cc-mage/pipelines/dataseeder_fileload/metadata.yaml
Add a new `datasource_description` field to the `datasource` table in SQL scripts and update the related YAML metadata files.
This change is being made to include additional descriptive metadata for each datasource, enhancing clarity and completeness of the data model. The introduction of the `datasource_description` field is aimed at providing better context and documentation for each datasource entry, improving data management and analysis processes.
> Micro sprint datasource description

- cc-mage/data_loaders/update_dataseeder.sql
- cc-mage/datasets/datasource_seeder.yaml
Filter out specific publishers from the data seeder due to data quality concerns and ensure constraints are maintained by removing any empty datasource entries.
To address constraint violations by omitting publishers with known data quality issues ('EDGAR', 'IEA', 'EPA') and to keep the datasource table clean by removing entries that do not comply with the updated filters. This approach improves data integrity and maintains reliable data seeding operations.
> fix: contraint violations in data seeder

- cc-mage/data_exporters/ghgi_methodology_methane_commitment_staging.py
- cc-mage/data_exporters/update_formula_input_waste_composition.sql
- cc-mage/data_exporters/update_ghgi_methodology.sql
- cc-mage/data_exporters/waste_composition_staging.py
- cc-mage/data_loaders/formula_input.sql
- cc-mage/data_loaders/import_s3_region_lookup_prioritised.py
- cc-mage/data_loaders/import_s3_waste_composition_values.py
- cc-mage/markdowns/carbon_content_context_solid_waste.md
- cc-mage/markdowns/waste_composition_context.md
- cc-mage/pipelines/db_create_table/metadata.yaml
- cc-mage/pipelines/ghgi_formula_input_waste_composition/metadata.yaml
- cc-mage/transformers/transformation_carbon_content_solid_waste.py
- cc-mage/transformers/transformation_raw_waste_composition_values.py
Add processes to stage and integrate methane commitment methodologies and waste composition data into the Global API pipeline.
These changes implement a structured approach to processing methane emissions data by mimicking IPCC guidelines, in order to help cities without detailed datasets estimate methane contributions from municipal waste. This enhancement fills the data integration gap with accurate source and methodology metadata while maintaining global applicability.
> feat: pipeline waste composition values in Global API

- cc-mage/datasets/datasource_seeder.yaml
Correct the dataset names in `datasource_seeder.yaml` for version 2023.
To ensure consistency and accuracy of dataset names in compliance with the naming conventions for the 2023 version, addressing any discrepancies in the current file.
> fix: datasets names version 2023

- cc-mage/data_exporters/update_activity_subcategory.sql
- cc-mage/data_exporters/update_emissionfactors.sql
- cc-mage/pipelines/ghgi_ipcc_sector1_emissions_factor/metadata.yaml
Revise the logic for determining `activity_subcategory_type` and `activity_id` in SQL scripts and update the execution statuses in the YAML metadata file.
The changes introduce conditional logic based on `gpc_reference_number` to accurately categorize different fuel types according to defined sectors, improving the categorization in conformity with business rules. Adjusting the metadata execution statuses ensures that the system accurately reflects the current operational state after the logical changes to ensure data integrity and processing accuracy.
> fix: adapted activity_subcategory_type logic
